const routes = {
  HOME: "/",
  CARDS: "/cards",
  BOXICONS: "/boxicons",
  TABLE: "/table",
  DOCUMENTATION: "/documentation",
  FORGOT_PASSWORD: "/forgotpassword",
  LOGIN: "/login",
  SIGNUP: "/signup",
  SUPPORT: "/support",
  ACCOUNT: "/account",
  NOTIFICATIONS: "/notifications",
  CONNNECTIONS: "/connections",
  ERROR: "/error",
  UNDERMAINTENANCE: "/undermaintenance",
  // User InterFace DropDown Pages
  ACCORDION: "/",
  ALERTS: "/",
  BADGES: "/",
  BUTTONS: "/",
  CAROUSEL: "/",
  COLLAPSE: "/",
  DROPDOWNS: "/",
  FOOTER: "/",
  LISTGROUPS: "/",
  MODALS: "/",
  NAVBAR: "/",
  OFFCANVAS: "/",
  PAGINATIONS: "/",
  PROGRESS: "/",
  SPINNERS: "/",
  TABSANDPILLS: "/",
  TOASTS: "/",
  TOOLTIPANDPOPOVERS: "/",
  TYPOGRAPHY: "/",
};

export default routes;
